steps:
 
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/alligrader2018/gradebook:$REVISION_ID', '.']

images: ['gcr.io/alligrader2018/gradebook:$REVISION_ID']
